export enum VideoGameGenreEnum {
  Action = 'Action',
  Adventure = 'Adventure',
  RolePlaying = 'Role Playing',
  Shooter = 'Shooter',
  Sports = 'Sports',
  Racing = 'Racing',
  Strategy = 'Strategy',
  Simulation = 'Simulation',
  Puzzle = 'Puzzle',
  Fighting = 'Fighting',
  Platformer = 'Platformer',
  Stealth = 'Stealth',
  Horror = 'Horror',
  OpenWorld = 'Open World',
  Sandbox = 'Sandbox',
  MMO = 'Massively Multiplayer Online',
  Indie = 'Indie',
  Other = 'Other',
  Default = 'Default',
}
